### ISSUE TITLE
Sample value parameter for @ApiParam annotation

### ISSUE THREAD

**Issue by buremba** [swagger-api/swagger-core#1006]
@ApiModelProperty has an 'example' property that allows us to provide a sample value however it seems @ApiParam doesn't support this feature yet. It would be nice to add this parameter to @ApiParam in order to make the API documentations more practical.

**Comment by webron** [comment]
`@ApiParam` doesn't have an example property to it because there's no equivalent in the specification itself so there won't be a way to represent it.

During the discussions around Swagger 2.0, some people raised it as an option but eventually we decided to not include it.

**Comment by buremba** [comment]
In my opinion, ApiModelProperty.example without ApiParam.example does not really make sense. I actually asked this question on IRC channel and @fehguy suggested me to file this issue.
@webron Is there any specific reason that you don't have any plans to include this parameter in swagger-spec and swagger-core?

**Comment by fehguy** [comment]
@buremba oops, that is my mistake then.  If it's not in the spec, it shouldn't be filed as a ticket--I told you otherwise, I apologize.

**Comment by buremba** [comment]
@fehguy no problem. :+1:

**Comment by webron** [comment]
@buremba - the whole concept of examples/samples is much more complicated than it seems. I've been looking for the discussion regarding examples for params, but cannot find it right now. 

IIRC, the reason was simple - complex models have the examples in their definition, so there's no need to add those. For primitives, samples don't really add much info. If a field is of type `integer`, providing a sample of `123` is a bit pointless.
