### ISSUE TITLE
Reorganize JAX-RS Module

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1244]
We have 3 modules today:
1. jaxrs - generic JAX-RS 1.0 support.
2. jersey-jaxrs - including file upload support for Jersey 1.X.
3. jersey2-jaxrs - support for JAX-RS 2.0 (`@BeanParam`) and Jersey 2.X file uploads.

With the new extension mechanism in core 1.5.X, we should create mini-modules for more specific support:
1. jax-rs 1
2. jax-rs 2
3. Jersey 1/Jersey 2/RESTEAsy/Wink/CXF/... file upload support.

We can then create bundles for specific implementations which would include the relevant combination of jax-rs and file upload support. Eventually, most users would use these bundles.

This would also be an opportunity to drop the jax-rs and specific implementation (jersey/jersey2) as `compile` dependencies and make them `provided`. Swagger-Core doesn't need to bring in those dependencies as whoever uses swagger-core already has a working JAX-RS library they depend on, with their own version. This would ease dependency management.

**Comment by webron** [comment]
May also want to take #997 into account here.

**Comment by webron** [comment]
Related to #1031 as well.

**Comment by elakito** [comment]
Hi Ron,
As a temporal workaround that does not break nor change anything, I changed my local copy of SwaggerJersey2Jaxrs to use reflection to get the jersey's FormDataParam's value. With this change, I could use this swagger-jersey2-jaxrs in my cxf-3.x use case having @BeanParam without having any jersey2 dependency. Would you consider this as an option for 1.5.4 until the package is refactored in the future?

regards, aki

**Comment by elakito** [comment]
Hi @webron @fehguy 
I got another idea about this.

How about adding the jaxrs 2.0 BeanParam support into swagger-jaxrs using reflection. It seems we need reflection only for the annotation type check, the rest of the code has no jaxrs-2.0 reference, so it can be directly used there.

This means, we can keep the current build dependency for swagger-jaxrs, that is to use jsr311-api.
But in runtime, if we find jsr399 on the classpath, we can support BeanParam.

Here you can see the code in my repo
https://github.com/swagger-api/swagger-core/compare/master...elakito:work-1244b

Basically, I moved part of the code from SwaggerJersey2Jaxrs into DefaultParameterExtension.
(I haven't deleted the corresponding code from SwaggerJersey2Jaxrs yet, so technically speaking not "moved" but "copied" at the moment)

As the reflection usage is limited to a few lines, we can get rid of the lines cleanly once we move to jsr399 sometime at a major version update.

Initially, I created a version of swagger-jersey2-jaxrs using reflection to avoid referencing jersey2 class so that it can be used with or without jersey2. But this approach appears somehow unnatural that one needs to use a jar named swagger-jersey2-jaxrs.jar when actually not using jersey. So, I went for the other way by getting jaxrs 2.0 support in swagger-jaxrs so that it can be used with jsr311 or jsr399.

How do you think?

regards, aki

**Comment by fehguy** [comment]
Closing as old, we'll update the organization for 3.0 support.
