### ISSUE TITLE
Unable to Delete the swagger project folder because of long file names !!!!!

### ISSUE THREAD

**Issue by Srithar-ccs** [swagger-api/swagger-core#1275]
Hi i am not able to delete the project from the directory because long file name error.

![image](https://cloud.githubusercontent.com/assets/8614905/8776888/5191c5de-2ec2-11e5-8264-9a5421e3d665.png)

**Comment by webron** [comment]
This is more of an issue with your operating system than it is with the project. You can try asking in the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) and perhaps someone could suggest a solution. Otherwise, just search for a general solution to the problem (again, not related to swagger at all).
