### ISSUE TITLE
Multiple ranges of allowable values

### ISSUE THREAD

**Issue by mar612** [swagger-api/swagger-core#1334]
I noticed in the Pet Store example that one of the operations has an implementation note that valid order IDs are either <= 5 or > 10.  Just wondering, is it actually possible to set up allowableValues to specify the order ID has to be <= 5 or > 10 (i.e. two ranges of allowable values)?  If not, would it be possible/feasible to allow multiple ranges of allowable values in a future release?  Thanks!

**Comment by webron** [comment]
It's not possible, right now, no, and not because of a limitation of swagger-core but rather that's what the spec allows. Right now, this is taken from how JSON Schema works, which doesn't allow to define it, and that would make it more difficult to implement in future versions as well.

You are invite to open an issue on [swagger-spec](https://github.com/swagger-api/swagger-spec) and ask for this feature, and we'll see if we can incorporate it in future versions.

**Comment by mar612** [comment]
That's fine; I figured as much, but I just thought I'd ask to make sure.  Thanks for the speedy reply!
