### ISSUE TITLE
Specify vendor extensions on model properties

### ISSUE THREAD

**Issue by arnm** [swagger-api/swagger-core#1403]
I'm using the JAX-RS Providers to automatically serve up my swagger spec. I'm trying to add vendor extensions to model properties. How can this be done?

**Comment by arnm** [comment]
I am currently implementing vendor extensions on model properties with the ReaderListener functionality. Doing it this way meets all my requirements. Though I'd like to explore alternatives if possible.

**Comment by fehguy** [comment]
Use the `@Extension` annotation

**Comment by colinpollock** [comment]
I was confused reading this at first. @fehguy it sounds like you were saying it's currently possible to use `@Extension`, but extensions aren't a param for `@ApiModelProperty` ([the spec](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#extension) also says this). 

So until #1898 is done this won't be possible. Unless I'm misunderstanding something, which would be awesome since it'd be great if this were already possible.
