### ISSUE TITLE
Feature Request: Add support for deprecated on a definitions property

### ISSUE THREAD

**Issue by roykachouh** [swagger-api/swagger-core#1504]
I noticed operations can be marked deprecated. Do you guys think it would make sense to also allow for deprecating fields on a property. 

A specific use case might be when generating servers and clients, it would be nice to inform users that a property is deprecated and will be removed in the next major version of the api.

I can work on this if we feel there is value?

**Comment by webron** [comment]
Hi @roykachouh, this is something that's can't be done because it isn't supported by the spec itself.

You're welcome to look in [swagger-spec](https://github.com/swagger-api/swagger-spec) for an existing issue, and if you don't fine one, please open a new one to be considered for the next version of the spec.
