### ISSUE TITLE
Missing JAX-RS 2.0 module

### ISSUE THREAD

**Issue by ilgrosso** [swagger-api/swagger-core#1558]
While working on CXF support for Swagger, we have noticed that the `swagger-jaxrs` module is missing support for `@MatrixParam` and `@BeanParam`.

While supporting the former seems to be controversial (swagger-api/swagger-spec#69) at the moment - even though part of the JAX-RS 1.1 spec, the latter is instead currently implemented by `swagger-jersey2-jaxrs`, even if this is actually a standard JAX-RS 2.0 feature rather than Jersey's.

The initial work for adding such support is currently hold in the PR apache/cxf#100.

Is it fine if I provide a PR here to create a new `swagger-jaxrs2` module, and to refactor `swagger-jersey2-jaxrs` to work with it?

**Comment by webron** [comment]
There's no support for `@MatrixParam` because it is not supported by the Swagger spec - see https://github.com/swagger-api/swagger-spec/issues/69.

As for @BeanParam support, that's currently provided only by `swagger-jersey2-jaxrs` which *can* be used for CXF as well. As it currently stands, that's the module that supports JAX-RS2. Yes, it pulls in Jersey as well, but that shouldn't affect the application. See https://github.com/swagger-api/swagger-core/issues/1244.

**Comment by sberyozkin** [comment]
What is wrong with having a swagger-jaxrs20 which would be implementation neutral and a Jersey specific -jersey module that would depend on swagger-jaxrs20 ? 

BeanParam is not Jersey specific. swagger-jaxrs is not called swagger-jersey-jaxrs11. 
Would you consider splitting  this module into two, a neutral and Jersey specific ?

Cheers, Sergey

**Comment by ilgrosso** [comment]
I recognize now this issue is kind of duplicate of #1244 by @elakito

**Comment by webron** [comment]
Nothing is wrong with having it, we just never got around to changing the structure of the project. That's exactly what's suggested in #1244.
