### ISSUE TITLE
Jax-RS - Reused Subresources not picked up by JaxRsApiListingResource / Reader

### ISSUE THREAD

**Issue by osx2000** [swagger-api/swagger-core#1574]
In my project, I use an extensive hierarchy of nested Sub-Resources. 

For implementing "leaf" Sub-Resources I reuse the same Classes / Sub-Resources on multiple, different paths.

    0 Top Level Resource 
    01 Subresource A
    021 Reusable SubResource X
    022 SubSubResource S
    0221 Reusable SubResource X
    02 Subresource B
    021 Reusable SubResource X

My issue is that the Default Reader-class stops descending the Resource tree when it encounters a Sub-Resources it has encountered before, thus not picking up / rendering the complete API. 

I have a workaround - a custom Reader class with this change

    //if (subResource != null && !scannedResources.contains(subResource)) {
    if (subResource != null) {

and a corresponding CustomJaxRsApiListingResource class that calls it. 

However, I wonder if there is a way to fix this in the default implementation.

**Comment by fehguy** [comment]
Yes, I believe you are right, we are not recursing into subresources over and over.

**Comment by osx2000** [comment]
Then I believe there is no point in using Sub-Resources at all if I can't reuse them under a Root / Top Level Resource.

**Comment by webron** [comment]
I think @elakito did something related to that? My memory could be playing tricks on me.

**Comment by elakito** [comment]
The change that I made for 1.5.4 intended to prevent an infinite recursion by checking for the visited resources while scanning down the path to determine when to stop. So, you can have sub resources recursed along the different paths but you can't visit the same resource along the path more than once.

@webron @fehguy 
I think, to support what @osx2000 wishes (i.e., to be able to expand from path 0221 down), we will need a new notation for a resource-link in swagger-api, so that the swagger document is bounded but the UI can expand the path down on demand to represent an infinite recursion.

regards, aki

**Comment by elakito** [comment]
just a moment and correction.
@osx2000 you mean this X is a leaf resource? We could exclude the leaf resources from this recursive check. In that way, without adding a new notation, we can support such cases.

**Comment by elakito** [comment]
i just looked into it and i think a single liner should probably fix this issue.
i'll try it out with a test case and see if this is indeed the case...
