### ISSUE TITLE
@ApiOperation response schema not exist when @ApiResponses exists

### ISSUE THREAD

**Issue by lwojtysiak** [swagger-api/swagger-core#1728]
Version: 1.5.7

When using @ApiOperation annotation with response = Object.class -> in swagger.json I can found:
path-> XXX -> get -> responses -> 200 -> schema 

But when I declare ALSO @ApiResponses without response attribues, element schema not exist.

Example:
1.
```
@GET
@Path("/Pets")
@ApiOperation(
            value = "Finding pets",
            response = Pet.class, 
            responseContainer = "List")
    public List<Pet> getPets() {}
```
---
`"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#/definitions/Pet"}}}}`

2.
```
@GET
    @Path("/Pets")
    @ApiOperation(
            value = "Finding pets",
            response = Pet.class,
            responseContainer = "List")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "Invalid params"),
            @ApiResponse(code = 500, message = "Exception")
    })
    public Pet getPets() {}
```
---
`"responses":{"200":{"description":"OK"},"400":{"description":"Invalid params"},"500":{"description":"Exception"}}`
    

And because of that - in swagger UI there is no information about the model schema. I think that when swagger generates response = 200 and put there model -> it should also put model into @ApiResponse, when response attribute is null -> so the value in @ApiResponse is more important.

**Comment by webron** [comment]
That's the expected behavior. `@ApiOperation` assumes a return code of 200 if a response is described in it. It will be automatically overridden by an `@ApiResponse` with the same status code. So use one or the other, but not both. If you need to override the return code at the `@ApiOperation`, you can use [this](http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiOperation.html#code()).
