### ISSUE TITLE
Changing swagger basepath.

### ISSUE THREAD

**Issue by DenEwout** [swagger-api/swagger-core#1744]
Hi,

I'm having some trouble setting up swagger with resteasy. I'm also trying to package in swagger-ui in the war, by copying the contents of the swagger-ui's dist folder into my webapps folder.

- [web.xml](https://gist.github.com/DenEwout/a44d801334bbe84fdde2f2f9280bfbb8)
- [PetstoreApplication.class](https://gist.github.com/DenEwout/778dea3a60db23ed01f8eb848f432200)

Now the problem I have with this is the following, configured like this, the swagger spec is located at localhost:8080/swagger.json. 

I'd like to have the swagger-ui sit at the root path and have the swagger.json be at /rest/api-docs (all other api's also start with /rest).

If I change the basepath in my application class nothing changes (the swagger.json still works at localhost:8080/swagger.json). 

If I change my servlet mapping in the web.xml alongside the basepath change, the swagger-ui shows up at the root path, my rest end points work, but the swagger.json is nowhere to be found.

What am I missing here?

Thanks for the help,

Ewout.

**Comment by webron** [comment]
The location of the swagger.json is not determined by the basePath configuration. The basePath points to the base path of *your* API.

The `io.swagger.jaxrs.listing.ApiListingResource.class` which you add as a resource is what exposes the swagger.json, and since it's loaded as part of your REST resources, it shares the same root as the other resources (in this case, as it seems "/"). 

If you want to change that, simply extend the class, add your own `@Path("...")` to it, and that should be hosted where you want.

**Comment by DenEwout** [comment]
Thanks, that did it.
