### ISSUE TITLE
Can we integrate swagger with ear (with multiple war file) in JBOSS

### ISSUE THREAD

**Issue by dineshpandiana** [swagger-api/swagger-core#1933]
we are deploying our app as as ear and ear contains mulitple war file with different context path.
we have added the swagger as module in jboss and used as dependency in ear.

Is swagger supports doc in ear? If there is any doc or link to guide to integrate with ear?
Please help.

**Comment by webron** [comment]
It really boils down to dependency management, classloaders and visibility. Since each application server has its own mechanism (which can also change between major versions), it's up to you to find the way to do it. I'm afraid we don't have the capacity to try and figure it out for every configuration out there.
