### ISSUE TITLE
Swagger mule module doesn't support @BeanParam annotation

### ISSUE THREAD

**Issue by f1sherox** [swagger-api/swagger-core#1944]
Support of BeanParam annotation was implemented in swagger-jersey2-jaxrsmodule. However mule module depends on swagger-jersey-jaxrs. Is there any obstacles to change dependency?

**Comment by webron** [comment]
I'm afraid so, yes. We officially don't support Mule 3.6 and above, and that goes beyond the support for BeanParam. Mule 3.6 made significant changes and we haven't gotten around to updating the project to support and be able to work with it.

To give you an idea, from their docs:
> Mule 3.6 makes use of Jersey v2.11, while older versions of Mule used Jersey 1.6. 

Now, I don't know if you ever had the pleasure of working with Jersey 1.6, but that thing was ancient when Mule 3.4 and 3.5 came out, and we needed to work around some things to get it to work. On top of that, as mentioned, 3.6 made significant infrastructure changes.

**Comment by f1sherox** [comment]
Thanks for reply, webron.

**Comment by DerEineDa** [comment]
I am sorry, but could you please elaborate? 

BeanParam annotations are completely handled by the module "swagger-jaxrs" inside class "Reader.java" (referenced by reflection). The module "swagger-jersey2-jaxrs" doesn't reference BeanParam at all, except for an unused import statement. 

In fact, we are using BeanParam in our project without using Jersey or any Jersey-Swagger-modules at all. 

I am missing something here?

**Comment by f1sherox** [comment]
The problem apears only with swagger mule module. [https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-mule](url)

**Comment by DerEineDa** [comment]
Yes, but the swagger-mule module depends on the swagger-jaxrs module and uses its Reader, thus should handle BeanParam annotations just fine. 

In fact, swagger-mule contains nothing else than the class ApiListingJSON to serve the swagger.json.

Maybe I am missing something essential here...

**Comment by webron** [comment]
swagger-mule does not work with Mule 3.6 and above - `@BeanParam` or no `@BeanParam`. If @DerEineDa is using `@BeanParam`, then they are using Mule >= 3.6.

**Comment by DerEineDa** [comment]
Nope, we aren't using any Jax-RS implementation. Our webservice implementations just happen to look a lot like Jax-RS services, so we are only using swagger-jaxrs together with a tiny Jax-RS annotations library. The annotations are only used to be parsed by swagger.

Even without using swagger-jersey(2), BeanParam annotations are handled by swagger-jaxrs just fine.

**Comment by webron** [comment]
What does that have to do with swagger-mule not working with Mule >= 3.6?

**Comment by DerEineDa** [comment]
nothing, but my case is that the one thing has nothing to do with the other. The question of this issue is bad. 

Yes, swagger-mule may not work with new versions of mile, but that has absolutely nothing to do with the support of BeanParam. BeanParam is supported by swagger-jaxrs, thus it is supported by any module depending on it, even swagger-mule. 

swagger-mule does only provide the api listing anyway. "support of BeanParam"  and "support of mule 3.6", these issues have nothing in common. This is my point.

**Comment by DerEineDa** [comment]
To add to this: The first sentence of this issue was "Support of BeanParam annotation was implemented in swagger-jersey2-jaxrsmodule". At least with the current code base, this statement is false. Support of BeanParam is currently not handled by swagger-jersey2. I just wanted to correct this obviously wrong assumption.

**Comment by webron** [comment]
Yes, the logic of dealing with BeanParam was moved between the two classes, and thank you for pointing that out. However, considering the OP mentioned they use swagger-mule, that doesn't affect the core issue at all. They still can't use it. They won't be able to use it even if they don't use the swagger-mule module and try to use other swagger-core modules, including extending their own Reader, without making fundamental changes to the core code of swagger-core.
