### ISSUE TITLE
Add vendor extensions to the Xml class

### ISSUE THREAD

**Issue by navidsh** [swagger-api/swagger-core#2164]
According to the OpenAPI spec v2.0, [XML object](http://swagger.io/specification/#xmlObject) should have vendor extensions.
However, `io.swagger.models.Xml` is missing the vendor extensions.

**Comment by navidsh** [comment]
`equals(Object)` and `hashCode()` need to be updated once vendor extensions is added.

**Comment by fehguy** [comment]
@navidsh since v3 of the OAI Spec is almost out, we won't update this version unless absolutely necessary.  Do you have a case that requires it?  If so, I ask that you provide a PR.

If you're interested in V3, please look here for the current working models:

https://github.com/swagger-api/swagger-core/tree/feature/3.0.0-rc0/modules/swagger-models

**Comment by navidsh** [comment]
@fehguy Sounds good. I'll close this one and #2162 that is similar to this issue. Thanks
