### ISSUE TITLE
Spring Boot @PathVariable and @ApiParam not works

### ISSUE THREAD

**Issue by mmaryo** [swagger-api/swagger-core#2318]
Hello

I use spring params converter and convert and Spring to Shop

But Swagger don't understant that and add all ShopEntity fields in param request in Json 

And @ApiParam(name = "id", type = "string") not works

    @RequestMapping(value = "{id}", method = RequestMethod.GET)
    @ApiOperation(value = "Find shop by id", response = ShopDto.class)
    public ResponseEntity<ShopDto> shopFindById(@PathVariable("id") @ApiParam(name = "id", type = "string") @NotBlank ShopEntity shop) {
        return ok(() -> shop);
    }

is it a bug or bad usage ?

**Comment by balajikandavel** [comment]
Just encountered the same issue.

**Comment by nickeeromo** [comment]
I did this as well, but I believe it is just bad usage. In REST, @PathVariables are expected to be an identifier of the path that precedes (in the original example here, pathvariable is "id", and presumably, the pathing is /shops/{id}. We don't need a description of what it is because it is self-explanatory. Makes sense I guess.

My issue was that with Spring Security in my application, for some reason, it actually caused an exception that was viewed as an unauthorized request to /swagger-ui.html (and yes, all the swagger paths were whitelisted). I commented all my controller methods out one by one to solve the problem.

With that said, I wish there was some sort of validation, like if the IDE could tell you "Hey, you can't do that." Now THAT would be helpful.

**Comment by webron** [comment]
Swagger Core does not support Spring Boot, it's intended for JAX-RS only. For Spring-based applications, please try Springfox or Springdoc.
