### ISSUE TITLE
@ApiModelProperty#readOnly() ignored

### ISSUE THREAD

**Issue by rtomsick** [swagger-api/swagger-core#2379]
Basically, whenever swagger determines (incorrectly) that a property is read-only due to a lack of setters on a model class (see #2169), there appears to be no way to mark it otherwise.  

Example

```java
@ApiModel("foo")
public class Foo
{
    private final int bar;

    @JsonCreator
    public Foo(@JsonProperty("bar") int bar)
    {
        this.bar = bar;
    }

    @JsonGetter("bar")
    @ApiModelProperty(value = "some description", readOnly = false)
    public int getBar(){return 0;}
}

```

This class is immutable, but Jackson handles serialization/de-serialization just fine.

Unfortunately, for the API spec we get:

```json
"foo" : {
      "type" : "object",
      "properties" : {
        "bar" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "some description",
          "readOnly" : true
        }
      }
    }

```

So basically, right now the situation is that if you use immutable model classes you're pretty much just screwed with no workaround. 

 Ideally #2169 will get fixed, but at the very least I would suggest at the very least that `@ApiModelProperty#readOnly()` be honored.

**Comment by rtomsick** [comment]
Well... at least there sort of is a workaround.  See my comment in #2169 for an example.

**Comment by bjchambers** [comment]
This also comes up if you're using any kind of immutable-POJO (eg., AutoValue, Immutables, Lombok). You end up with a POJO like:

```
@Immutable.Value // or @AutoValue, etc.
public abstract class Foo {
  public abstract int bar();
}
```

You can modify the values using the generated builder, but the properties in the model are reported as readOnly even if you explicitly set them to readonly in the annotation.

**Comment by bjchambers** [comment]
It looks like there are several problems causing this, any of which could fix it:

1. A variable `readOnly` is set based on whether or not a setter is defined in the model:
https://github.com/bjchambers/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L371

2. This variable is updated based on the value of the readOnly field in the annotattion:
https://github.com/bjchambers/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L391

Note that this only happens if the value of the readOnly field is `true`, so this doesn't help.

3. The value of read only in the property is set using the `_findReadOnly` method.

https://github.com/bjchambers/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L496

Note that this duplicates the lookup that happened in 2. It also *correctly* calls `setReadOnly(false)`.

4. Then, if the property currently has a value of `null` for getReadOnly, it is overwritten with the field.
https://github.com/bjchambers/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L501

5. `AbstractProperty.setReadOnly(...)` has the following:

```
    public void setReadOnly(Boolean readOnly) {
        if (Boolean.FALSE.equals(readOnly)) {
            this.readOnly = null;
        } else {
            this.readOnly = readOnly;
        }
    }
```

https://github.com/bjchambers/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java#L207 

---

So, there seems to be two places where the value of the property is looked up is considered, but in both places the value is ignored. 

In the first, the variable `readOnly` is only set to true if the annotation has a true value, so it is impossible to use the annotation to set the desired value.

In the second, we extract and pass the right value to `setReadOnly`, but since it is false we turn it into null, and then overwrite it with the incorrect value of the field.

Not being familiar with the intentions of this code, it seems like there are several possibilities:

1. Treat `null` and `false` differently in `AbstractProperty`. One can be "not explicitly set" and the other "explicitly set to false". I have verified that changing the behavior of `setReadOnly` to be `this.readOnly = readOnly` fixes the problem.

2. Change the logic in `ModelResolver` to be something like:

```
Boolean isReadOnly = _findReadOnly(member);
if (isReadOnly == null) {
  isReadOnly = !hasSetter;
}
property.setReadOnly(isReadOnly);
```

The first option seems to be the smallest fix but affects the semantics of the read only property, while the second is a bit larger, but removes duplication of some logic and seems to generally clean things up.

I'm happy to send a quick PR to fix this someone familiar with the intentions can suggest the proper fix?

**Comment by bjchambers** [comment]
One problem with fixing this is that it changes the behavior of the default value. For instance:

```
@ApiModelParameter(value = "foo")
public int getFoo() { ... }
```

The default value has `readOnly = false`, which was previously being ignored, resulting in an API that indicated read only is true. Now it would respect the default, so the resulting API indicates it is not read only.

**Comment by frantuma** [comment]
Thanks @rtomsick and @bjchambers for reporting and analyzing this; PR #2675 introduces new `ApiModelProperty` field `accessMode` which replaces `readOnly` (deprecated) to allow setting readOnly both as `true` and `false` in `ApiModelProperty` annotation. 

This is part of latest `2.0.0-SNAPSHOT` available in sonatype and in upcoming release.

Current behaviour (without usage of `accessMode`) is left unaltered to maintain backward compatibility.

See [this test](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/models/ReadOnlyModelUpdated.java) for a usage example.

Closing ticket, please reopen if you still encounter issues.

**Comment by martayubero** [comment]
Given that `A variable readOnly is set based on whether or not a setter is defined in the model`, I was able to "cheat" swagger by having setters and make them private. This way the pojo is still immutable and the wrongly generated `readOnly: true` has disappeared.

**Comment by pablonautic** [comment]
As of mid 2020 the following code seems to do the trick:

    @ApiModelProperty(accessMode = ApiModelProperty.AccessMode.READ_WRITE)
    private String field;
