### ISSUE TITLE
Duplicate model names don't throw but are overwritten

### ISSUE THREAD

**Issue by bountin** [swagger-api/swagger-core#2538]
I'm using version 1.5.10 and experiencing the following issues: I have two classes with the same simple name but in different namespaces. When I generate my swagger file, one of them "wins" and overwrites the first one.

I've found a workaround to use a custom model name via `ApiModel`. Alternatevly, I could make use of one of the other name resolvers like Jackson's annotation.

But still, I'd like to detect such a name clash automatically and not by accident when the specs don't match the API. What do you think about adding a check [here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Swagger.java#L349)? I can provide a PR if wanted, just wanted to talk about it before.

Alternatively, I'd have to execute the same class scanning as Swagger does in order to find such a clash.

**Comment by mdzhigarov** [comment]
I am struggling with the same issue.
The ApiModel workaround doesn't work for me because I am using the swagger-maven-plugin with UseJAXBAnnotationProcessor option:

https://github.com/kongchen/swagger-maven-plugin/commit/dbe98e507c756c806431d8c80df06832617f27bd

(objectMapper.registerModule(new JaxbAnnotationModule());)

Any suggestions?

**Comment by Villane** [comment]
I ran into the same issue, where I have several JAX-RS resources where the models are defined as inner classes and sometimes they conflict. It's going to be a surprise each time because we don't track such conflicts any other way so they just show up as misinformation in Swagger.

**Comment by Splash34** [comment]
+1

**Comment by ccosentino** [comment]
+100
This is a huge issue for us.  We have hundreds of APIs and add more every month.  The fact that swagger silently overwrites models if they have duplicate names has caused a lot of issues; most importantly of which is that we cannot trust the swagger documentation. It would be nice if the scanner would at least log when it finds a duplicate api model. 

Keep in mind this is only manifests itself if you have two models with the same value but have different structures. In our case, we had many models with duplicate values, but the structures were the same. However, for many models with the same value, the models were similar but not identical, which caused further confusion since things looks mostly correct.

For those struggling with this, our solution was to write our own annotation scanner and search for apimodel annotations with a duplicate value, then going into the code and manually making them unique.  We are working this process into our pre-promote workflow. But it would be better if the tool didn't allow this to happen in the first place.

**Comment by amontenegro** [comment]
+1

**Comment by fleckb** [comment]
+1

**Comment by xingchch** [comment]
+100
this issue make the compiled binary file untrustworthy, so in fact ,this is a huge issue...

**Comment by betterment-ash** [comment]
Not sure this is helpful but I figured I'd add what worked for me.

Our use case is a Spring Boot application and we're adding Swagger UI. Our controllers often times have inner classes for requests and responses, but are often generically named `Request` and `Response`, which causes conflicts due to how the `DefaultTypeNameProvider`uses `type.getSimpleName()`:

https://springfox.github.io/springfox/javadoc/current/springfox/documentation/schema/DefaultTypeNameProvider.html

Our solution was to just create our own `TypeNameProviderPlugin`, which is a component on one of our `@Configuration`s

```
    @Component
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public static class CustomTypeNameProvider implements TypeNameProviderPlugin {
        @Override
        public String nameFor(Class<?> type) {
            String fullName = type.getName();
            return fullName.substring(fullName.lastIndexOf(".") + 1);
        }

        @Override
        public boolean supports(DocumentationType delimiter) {
            return true;
        }
    }
```

Found out about plugins via documentation here: https://springfox.github.io/springfox/docs/snapshot/#plugins

Hope this helps someone! 🤞

**Comment by bountin** [comment]
@betterment-ash Nice workaround! Sadly, it's just usable if you use springfox and not "just" swagger.

**Comment by hickkart** [comment]
Any ETA on when this will be resolved? Do we have any workaround in swagger.core?

**Comment by webron** [comment]
Just like any issue, PRs are welcome :)

**Comment by frantuma** [comment]
Custom naming can be obtain providing a custom `TypeNameResolver`, an example can be found [here](https://github.com/swagger-api/swagger-core/blob/1.5/modules/swagger-core/src/test/java/io/swagger/model/override/CustomResolverTest.java) naming models with fully qualified name, but whatever strategy could be applied, e.g. applying code similar to the springfox example above. Closing ticket please reopen if still experiencing issues

**Comment by csaroff** [comment]
@frantuma is it possible to reopen this issue? I know that it's many years old, but I think the main issue was that *duplicate model names don't throw*. This can be far from obvious in a large codebases with hundreds of models 

It would be really helpful to receive an error that a model name was duplicated rather than accidentally generating an erroneous specification.

**Comment by ClaudenirFreitas** [comment]
> [@frantuma](https://github.com/frantuma) is it possible to reopen this issue? I know that it's many years old, but I think the main issue was that _duplicate model names don't throw an exception_. This can be far from obvious in a large codebases with hundreds of models.
> 
> It would be really helpful to receive an error that a model name was duplicated rather than accidentally generating an erroneous specification.

➕

**Comment by daniel-kmiecik** [comment]
@ClaudenirFreitas due to the date this issue was created and the long history of changes in the project, please create a new issue and fill it in according to the template. This will certainly help in analyzing the problem. In addition, we encourage you to contribute and create fixes.
