### ISSUE TITLE
_1 added to some operation ids after upgrade from 2.0.0-rc3 to 2.0.0-rc4

### ISSUE THREAD

**Issue by ilgrosso** [swagger-api/swagger-core#2643]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug
| Which Swagger-Core version?       |2.0.0-rc4
| Which Java version?               |1.8
| Which JAX-RS framework & version? |CXF 3.2.2-SNAPSHOT
 

This [service class](https://github.com/apache/cxf/blob/master/systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/group1/BookStore.java) generates the following operations ids with 2.0.0-rc3:
* getBooks
* getBook
* delete

and the following operation ids with 2.0.0-rc4:
* getBooks_1
* getBook_1
* delete

Is there any reason for this?

**Comment by frantuma** [comment]
in rc4, as specification mandates a spec-unique `operationId`, a suffix is added if methods with same name  are resolved (regardless of class/resource) and `operationId` is not provided in `@Operation` annotation; with your example as is, this should't be the case, unless the above scenario is applicable.

**Comment by ilgrosso** [comment]
thx for your answer @frantuma 

As you can see from this [test setup](https://github.com/apache/cxf/blob/master/systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/openapi/OpenApiNonAnnotatedServiceDescriptionTest.java#L45-L46), the only service classes are [BookStore](https://github.com/apache/cxf/blob/master/systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/group1/BookStore.java) and [BookStoreStylesheetsOpenApi](https://github.com/apache/cxf/blob/master/systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/openapi/BookStoreStylesheetsOpenApi.java) - and no `operationId` conflict should generate from there.

**Comment by frantuma** [comment]
I suspect the root cause could be the configuration of `resourcePackages` by resolving package of the considered classes [here](https://github.com/apache/cxf/blob/1697c1f1cd1467860083140601ffa6cd14d12eaf/rt/rs/description-openapi-v3/src/main/java/org/apache/cxf/jaxrs/openapi/OpenApiFeature.java#L508), invoked [here](https://github.com/apache/cxf/blob/1697c1f1cd1467860083140601ffa6cd14d12eaf/rt/rs/description-openapi-v3/src/main/java/org/apache/cxf/jaxrs/openapi/OpenApiFeature.java#L134) and then used [here](https://github.com/apache/cxf/blob/1697c1f1cd1467860083140601ffa6cd14d12eaf/rt/rs/description-openapi-v3/src/main/java/org/apache/cxf/jaxrs/openapi/OpenApiFeature.java#L147) to fill OpenApi configuration `resourcePackages` field; in the test case, `BookStoreOpenApi` is also scanned/read as it belongs to passed package; as it provides the same `operationId` the suffix is added.

In this particular case, `BookStoreOpenApi` also provides the same paths/operations, which overwrites the ones from `BookStore`; I guess this is an edge case which probably is not intended, nor supported; however logic will probably be updated in next release to use the `operationId` without suffix in such a case.

Please let me know if this solves your issue.

**Comment by ilgrosso** [comment]
nice catch @frantuma - need to find a way through the tests, though...
