### ISSUE TITLE
Class Level @Produces and @Consumes Ignored

### ISSUE THREAD

**Issue by PeaceInColour** [swagger-api/swagger-core#2651]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug
| Which Swagger-Core version?       |1.5.18
| Which Java version?               |1.8
| Which JAX-RS framework & version? |RESTEasy 3.0.19 with JAX-RS 2.0
 

@Produces and @Consumes at the class level are ignored. These annotations at the method level have no issue. Using the produces and consumes parameters in @API is a workaround. For example:

```java
@Path("pathOne")
@Api 
@Produces(MediaType.TEXT_HTML)
@Consumes("application_json")
public interface SomeInterface {
	@GET
	@Path("pathTwo")
	Response SomeMethod();
}
```
will not have any values for produces or consumes for SomeMethod in the generated OpenAPI file.

**Comment by maksymgendin** [comment]
I am facing the same problem here and found your issue via Google 😄 

After some debugging I found the reason in `io.swagger.jaxrs.Reader`.
It happens only if you have in your classes-to-scan two classes - `SomeInterface` interface and for example `SomeInterfaceImpl` implementaion.
Swagger is able to correctly read the definiton from `SomeInterface` but then he reads the definiotion from `SomeInterfaceImpl` and overwrites the `consumes` and `produces` fields in that same operation with `null` (because your `SomeInterfaceImpl` for sure will not have any `@Consumes` and `@Produces` annotations).

To fix this issue the definitions from the interface should be somehow merged with those from implementation. There is even a possibility to provide `parentConsumes` and `parentProduces` in `io.swagger.jaxrs.Reader#read(...)`.

**Comment by frantuma** [comment]
Swagger is not considering annotations at superclass/interface level, according to JAX-RS spec par. 3.6:

`Note that inheritance of class or interface annotations is not supported.`

Annotations on superclass/interface at method/param level are instead supported, and should work ok in current version.
Closing ticket, please reopen if you're still experiencing issues.
