### ISSUE TITLE
Why does Swagger 3.0 not automatically scan all super types and generate allOf accordingly, but we have to manually input allOf via Schema annotation?

### ISSUE THREAD

**Issue by duckladydinh** [swagger-api/swagger-core#2863]
Dear all,

I have just checked the Swagger ModelResolver implementation and unexpectedly, it seems to me that Swagger 3.0 only fetches allOf information from the annotation. I was expecting that Swagger would use some reflection or something to automatically create allOf but it was not :'( .

Is this intended? May I know the reason? If it is because you are busy developing something else, I am happy to make it and contribute. What do you think?

Thank you.

**Comment by frantuma** [comment]
Generally speaking, mapping java composition/inheritance to JSON/JSONSchema/openAPI can be tricky due to to the different constructs and the like; in Swagger, the inheritance model is resolved by considering swagger specific annotations and  jackson `JsonTypeInfo` / `JsonSubtypes` annotations along with super classes and interfaces, let's say with an approach similar to Jackson's. 

That said, any improvement/added feature in this area is as usually more than welcome, not sure what you had in mind; it could be maybe possible in some scenarios to e.g resolve a parent/child pair with no annotations having the child define an `allOf` of properties of the parent, or something like that (which would work only if resolving the child, as when resolving the parent we will have no info about its subtypes), this would require probably some flag to be considered to activate such behaviour, and probably also some side effects to consider.
