### ISSUE TITLE
Reflections is causing issues with Tomcat

### ISSUE THREAD

**Issue by berkoab** [swagger-api/swagger-core#2943]
There is a bug in the Reflections class documented here: https://github.com/ronmamo/reflections/issues/81. It is not possible to run Swagger on Tomcat 7 without receiving the error: 
zip file closed
The author of Reflections has yet to create a release or release a patch for it although he has merged the fix into the main branch.

The fix is:

1. Downgrade Reflections to 9.9.
2. Use something else like https://github.com/classgraph/classgraph for resource scanning.
3. Use a different branch of Reflections that has the fix in it.

**Comment by devoto13** [comment]
The Reflections library also has several other bugs affecting Swagger users and haven't had a release for more than a year. I also would like to migrate to something more alive.

To name a few: 
- https://github.com/ronmamo/reflections/issues/205 which causes Reflections to attempt to read from all files types and print lots of parsing exceptions (fixed a year ago and not released since than).
- https://github.com/ronmamo/reflections/issues/171 and https://github.com/ronmamo/reflections/issues/190 which causes bunch of `java.lang.ClassNotFoundException` exceptions in some setups (in particular when using [shadow plugin](
https://github.com/johnrengelman/shadow).
- https://github.com/ronmamo/reflections/issues/241 seems to have issues with newer versions of Java, but I haven't faced this myself.

**Comment by hc-codersatlas** [comment]
Might be a good time now to switch to something compile time / annotation processed e.g. https://github.com/atteo/classindex ?

**Comment by frantuma** [comment]
#3109 addresses this by replacing [reflections](https://github.com/ronmamo/reflections) with [classgraph](https://github.com/classgraph/classgraph)
