### ISSUE TITLE
io.swagger.v3.jaxrs2.Reader#resolveApplicationPath does not work with proxies

### ISSUE THREAD

**Issue by nelsongraca** [swagger-api/swagger-core#2966]
The current implementation of resolveApplicationPath fails to find the @ApplicationPath annotation if the application is a proxy, it should search for the annotation in the superclass too.

I can provide a PR with a fix if needed.

**Comment by frantuma** [comment]
Thanks for reporting this, and yes a PR is welcome!

**Comment by nelsongraca** [comment]
Ok, I will work on it and submit it ASAP since this would be useful for me.

**Comment by frantuma** [comment]
I guess it's a good approach, shouldn't have side effecs

**Comment by nelsongraca** [comment]
Hi the PR is submitted: https://github.com/swagger-api/swagger-core/pull/2974

**Comment by frantuma** [comment]
Thanks! PR merged, closing ticket

**Comment by jgangemi** [comment]
this issue is still broken w/ version `2.0.8`. i'm using `helidon`, which in turn uses `weld` and stepping through the code, it seems the logic is reversed. the `ResourceConfig` is found where the weld proxy is looked for and the proxy is found where the resource config is looked for, specifically when `application.getClass().getMethod("getApplication", null);` is invoked.
