### ISSUE TITLE
ApplicationPath not added by swagger-maven-plugin

### ISSUE THREAD

**Issue by martin-v-ottesen** [swagger-api/swagger-core#3060]
<plugin>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-maven-plugin</artifactId>
    <version>2.06</version>
</plugin>

 Does not add the ApplicationPath in the openapi files.

**Comment by deBFM** [comment]
Having the same problem with 2.0.7

**Comment by wallaroo** [comment]
same for 2.0.8

**Comment by webron** [comment]
Please consider submitting a PR.

**Comment by borramTAS** [comment]
same for 2.1.6

**Comment by adagios** [comment]
To mitigate this issue I ended up creating a ReaderListener that modifies the Paths and adds the needed top level path.

Something like:
```
@OpenAPIDefinition //just so that it's picked up by the class scanner
public class BasePathModifier implements ReaderListener {

    @Override
    public void beforeScan(OpenApiReader openApiReader, OpenAPI openAPI) {
    }

    @Override
    public void afterScan(OpenApiReader openApiReader, OpenAPI openAPI) {
        Paths paths = openAPI.getPaths();
        Paths modifiedPaths = new Paths();

        paths.forEach((path, pathItem) -> {
            modifiedPaths.addPathItem("/SOME_BASE_PATH" + path, pathItem);
        });

        openAPI.setPaths(modifiedPaths);
    }
}
```

I did have to annotate it with `@OpenAPIDefinition` so that it was picked up by the [JaxrsAnnotationScanner](https://github.com/swagger-api/swagger-core/blob/438230d79d4597d6b703437a03c32cdbf8a28ba5/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/JaxrsAnnotationScanner.java#L92).

Hope it helps!

**Comment by frantuma** [comment]
since version `2.1.9` (#3936) a new boolean configuration parameter `alwaysResolveAppPath` is available: if set to `true` `@ApplicationPath` annotation applied to a JAX-RS `Application` class will be considered also at build time (e.g. via maven/gradle plugin or programmatic execution) and when exposing via a separate app (e.g. via `OpenAPIServlet`).
