### ISSUE TITLE
Double encoding in swagger-ui

### ISSUE THREAD

**Issue by mykhailokulakov** [swagger-api/swagger-core#315]
In GET request space character encodes like %2520. I think it happens because '%' has 25 code. So space character encodes into %20 and after that '%20' into %2520. It happens in different browsers with different encoding settings. It started after migration to new swagger 1.3.0.

I use postmen to test this service directly, and it works fine. 

For example i send 'parameter one' as get parameter through swagger-ui. 
In header we will see: 
Request URL:http://.../parameter%2520one/...

I have found this: 
https://github.com/wordnik/swagger-ui/issues/301
But this update didn't help me

I've found solution
swagger.js
line 832

SwaggerOperation.prototype.urlify = function(args) {
      ....
Here is it encodes first time:
            url = url.replace(reg, encodeURIComponent(args[param.name]));
          ....
      }
     .....
And here is second time
            queryParams += encodeURIComponent(param.name) + '=' + encodeURIComponent(args[param.name]);
          }
        }
      }
     ....
    };
I've changed it to:
queryParams += encodeURIComponent(param.name) + '=' + args[param.name];
Fix this please) 

This issue should be moved to swagger-ui section

**Comment by mojidabckuu** [comment]
I also faced with this issue even now if you go to petstore. Swagger code users 2 places of url building. If you put string inside url prompt without http it will add extra. In second case it adds self.sheme in 4096 line inside swagger-ui.js.

![screen shot 2015-11-17 at 12 03 36 pm](https://cloud.githubusercontent.com/assets/1161058/11205724/5779c2ac-8d23-11e5-8940-bbe1bfafa98c.png)
![screen shot 2015-11-17 at 12 03 25 pm](https://cloud.githubusercontent.com/assets/1161058/11205729/60e31992-8d23-11e5-9c49-470002c32702.png)

**Comment by st411ar** [comment]
I faced with this issue again in formData string parameter of the content-type "application/x-www-form-urlencoded". String "% @" are encoded to "%2525%2520%2540" instead of "%25%20%40".

![screenshot_1](https://cloud.githubusercontent.com/assets/15057618/26745420/16ef954a-47f3-11e7-8483-29a1e4698bc4.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15057618/26745439/36733be2-47f3-11e7-950c-190fd834267f.png)

**Comment by fehguy** [comment]
Hi @st411ar I've opened this issue with the SwaggerHub team.  If you could, please contact support there via https://community.smartbear.com/t5/SwaggerHub/ct-p/SwaggerHub

**Comment by sowmya-sakhamuri** [comment]
Hi, I am using Swagger Editor editor.swagger.io. I have written my swagger documentation using openapi 3.0 and I have also used allowReserved = true for my query parameter.
The problem is if my query parameter value contains '%' symbol, it is taking as '%25'. I need to avoid this encode and it should go as '%' symbol only. Please suggest.

**Comment by maruarcus** [comment]
Hi @sowmya-sakhamuri probably you fixed it already but I still want to share my solution: I have fixed it by changing the `swagger-ui-bundle.js` file I had to because newer versions of swagger get rid of hmac authentication in this specific file so the work around is the following: 

Decode the url within the `encodeURI` method in 3 different parts of the file:

1. look for this section of code

`{var o=[i,r,t,n];return y.default.createHmac("sha1",e).update(o.join(",")).digest("base64")}(t,encodeURI(r),l,s,i)}}`

and add `decodeURI` within `encodeURI` as such:

`{var o=[i,r,t,n];return y.default.createHmac("sha1",e).update(o.join(",")).digest("base64")}(t,encodeURI(decodeURI(r)),l,s,i)}}`

2. look for this other section of code

`,c.default.createElement("div",{className:"request-url"},c.default.createElement("pre",null,encodeURI(l)))))}}]),LiveResponse}`

and add `decodeURI` within `encodeURI` as such:

`,c.default.createElement("div",{className:"request-url"},c.default.createElement("pre",null,encodeURI(decodeURI(l))))))}}]),LiveResponse}`

3. lastly look for this section of code

`curl(e){var t=[],r="",s=e.get("headers");if(t.push("curl"),t.push("-X",e.get("method")),t.push('"'+encodeURI(e.get("url"))+'"'),s&&s.size)`

and add `decodeURI` within `encodeURI` as such:

`curl(e){var t=[],r="",s=e.get("headers");if(t.push("curl"),t.push("-X",e.get("method")),t.push('"'+encodeURI(decodeURI(e.get("url")))+'"'),s&&s.size)`
