### ISSUE TITLE
@ExampleObject missing description

### ISSUE THREAD

**Issue by pioto** [swagger-api/swagger-core#3341]
It seems that the `@ExampleObject` annotation doesn't provide a `description` field, as defined in https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#exampleObject

Instead, it seems to copy the `name` over as a `description` in the generated schema, which ends up looking weird.

If I'm reading things right, the fix should be to both add a `String description() default ""` to `io.swagger.v3.oas.annotations.media.ExampleObject`, and to adapt the schema generation to code to use this field, and default it to nothing instead of the name.

**Comment by estroykov** [comment]
Any updates here?

I would like to make some more points. In Open API, example name is supposed to be a rather short and it must adhere regular expression `^[a-zA-Z0-9\.\-_]+$` (see [specification](https://swagger.io/specification/) → Ctrl + F → must use). In particular, one can not use spaces in example name.

On the other hand, example description is supposed to be a human readable text which has to contain spaces (and therefore it can not adhere regular expression mentioned above).

So, since Swagger generator uses `name` as `description`, one can not provide human readable description for example.

**Comment by frantuma** [comment]
Thanks for reporting this. `description` field has been added in #3353 and is available in latest snapshot and upcoming `2.0.11` release.

**Comment by estroykov** [comment]
@frantuma, thank you for such a quick fix!
