### ISSUE TITLE
Defining header with default value

### ISSUE THREAD

**Issue by MugdhaB** [swagger-api/swagger-core#3398]
For all our product apis, we have to set Accept header default value to application/json;api-version=1.0. Is there a way to achieve this?
Attaching a snapshot of achieving the same through springfox. 
![image](https://user-images.githubusercontent.com/5356273/71713910-a5e8e400-2e31-11ea-9b74-2a5c9648db17.png)

**Comment by webron** [comment]
Since you've mentioned Springfox, you should file the issue with that project. We don't control how it uses our annotations.

That said, the OpenAPI specification does not allow API definition to explicitly define the `Accept` header. The way to control it differs based on whether you're using [v2](https://swagger.io/docs/specification/2-0/mime-types/) or [v3](https://swagger.io/docs/specification/media-types/).
