### ISSUE TITLE
List of Enums does not show the list of enum values in the Swagger schema

### ISSUE THREAD

**Issue by jknova** [swagger-api/swagger-core#375]
Hello,

If I have the model:

```
public class ATM
{
    public enum Currency
    {
        USA,
        CANADA
    }

    private List<Currency> supportedCurrencies;
}
```

The generated model in the schema would like something like:

```
ATM": {
    "id": "ATM",
    "description": "",
    "properties": {
        "supportedCurrencies": {
            "$ref": "array",
            "description": "",
            "items": {
                "$ref": "Currency"
            }
        }
    }
}
```

But there's no mention of the available enum values. Is it possible to fix this, and if so, what should the model look like?

Would there just be an extra enum property under 'supportedCurrencies', or would the enum property appear under 'items'?

Thanks

**Comment by shankar96** [comment]
I have following enum  for generation of enum i like to display  successValue and okValue instead of just OK and SUCCESS. Any help would be appreciated
`package com.main;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(using = SerialiazerEnum.class)
public enum ActionType {
    SUCCESS("successValue"),
    OK("okValue");
    private final String value;

    ActionType(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }

}
`
