### ISSUE TITLE
Why does specifying OpenAPI 3.1.0 remove all "type" properties?

### ISSUE THREAD

**Issue by Yaytay** [swagger-api/swagger-core#4296]
I'm working on a pretty basic REST API with quite a complex object model.
The only differences between the output when:
`openAPI31(Boolean.TRUE)`
and
`openAPI31(Boolean.FALSE)`
are:

1. All of the "type" properties have been removed from the Schema properties.
2. The version number has changed.
3. The jsonSchemaDialect is specified.

An example subset from OpenAPI 3.0.1:
```
  "components" : {
    "schemas" : {
      "Directory" : {
        "type" : "object",
        "properties" : {
          "path" : {
            "type" : "string"
          },
          "modified" : {
            "type" : "string",
            "format" : "date-time"
          },
          "name" : {
            "type" : "string"
          },
          "children" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Node"
            }
          }
        }
      },
```
and from 3.1.0:
```
  "components" : {
    "schemas" : {
      "Directory" : {
        "properties" : {
          "path" : { },
          "modified" : {
            "format" : "date-time"
          },
          "name" : { },
          "children" : {
            "items" : {
              "$ref" : "#/components/schemas/Node"
            }
          }
        }
      },
```

Is this something a bug in the OpenAPI library, or am I missing something on my side?

It's not just string "types" that are missing, they've all gone.

I have specified dependencies on swagger-jaxrs2-jakarta:2.2.6 and swagger-annotations-jakarta:2.2.6.

Thanks.

**Comment by frantuma** [comment]
from your outcome above I suspect that the spec gets serialized using the 3.0 `Yaml` class instead of the 3.1 `Yaml31`. Can you share some more details about your scenario (how are you integrating Swagger, how do you serialize the spec, etc)?

Please see also [this comment] for some details about 3.0 Schema [`type`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L52) vs 3.1 [`types`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L111)

**Comment by Yaytay** [comment]
Hmm, well now it's working and I don't know why :(
I suspect I had invalid combinations of dependencies somewhere.
I'm going to close this issue, but I'd be really grateful if you could give me the actual link to type vs types differences.

**Comment by Yaytay** [comment]
It's working for me now.

**Comment by frantuma** [comment]
Updated link to [related comment](https://github.com/swagger-api/swagger-parser/issues/1821#issuecomment-1300918559)

**Comment by daniferna** [comment]
Hello @Yaytay,

I am facing the same issue. Do you remember what was the exact cause for this behavior? Could you explain a little more in-depth how you fixed it?

Thanks in advance and kind regards!
