### ISSUE TITLE
Is swagger-core 2.2.7 compatible with Java 17?

### ISSUE THREAD

**Issue by leolimas** [swagger-api/swagger-core#4331]
Is the swagger-core project compatible with Java 17? I'm upgrading my projects to Springboot 3.0.0 and Java 17... 
Just now after getting the head over wall I remember check this... There any adjust that I need to run it on Java 17 or it is transparent?

**Comment by Colsarcol** [comment]
Not sure if it will help you but I was also having issues using Java 17 as well. I kept getting an stack trace that had javax in it, seeing as java 17 switch to jakarta. I was using the wrong versions of dependencies, come to find out there is a -jakarta version of the swagger dependencies. 

Example:
https://repo1.maven.org/maven2/io/swagger/core/v3/swagger-models-jakarta/

**Comment by frantuma** [comment]
As mentioned by @Colsarcol  Swagger Core provides separate jakarta artifacts (with `-jakarta` suffix). Please check [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#note-jakarta-namespace-support-since-version-217) for some more details

Closing ticket, please reopen if still experiencing issues
