### ISSUE TITLE
consider updating artifact names

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#798]
For 1.5, we might want to update the artifacts from com.wordnik.* to io.swagger.*.  We shouldn't update the package names inside the code until 2.0 to keep drop-in compatibility, but since the version will need an update, this might be a good time to make the change.

**Comment by webron** [comment]
We may consider releasing an interim version as 1.6 with the new package names. We can either do that after 1.5 is final or alongside, though maintaining that would be a pain. It'll easier for new users to adopt 1.6 and for existing ones to just migrate to 1.5 from 1.3.

**Comment by todd-richmond** [comment]
1.5 has enough major changes that it seems like a reasonable, though not huge effort is already required to migrate from 1.3. In that case, changing package names at the same time is trivial

Why not just make the change now? We're already working on 1.5 milestone releases and so expect some churn

**Comment by webron** [comment]
@todd-richmond - we want to make the transition to 1.5 from 1.3 as seamless as possible. Some people wouldn't mind doing a mass find&replace, but some may be wary of making such a huge commit initially.

**Comment by talton-rmn** [comment]
I'd like to see the artifact name change.  I'm working on a project that's trying to consume swagger documentation, and it'd be a lot easier to support both v2 and v1.2 specs if I could re-use the parsing logic from swagger-core.  At the moment, it looks like I can only use either the v2 parser or the v1.2 parser due to classpath conflicts (Unless I copypasta the code from the different versions - not my favorite plan)

**Comment by fehguy** [comment]
@talton-rmn can you use the new swagger-parser project, which consumes both formats?

**Comment by talton-rmn** [comment]
@fehguy - Looks like that will do perfectly.  Thanks for sharing that - not sure how I missed it in the first place.

**Comment by fehguy** [comment]
Great--it's a fairly new project.  I'm closing this out.
