### ISSUE TITLE
dataType field for ApiParam

### ISSUE THREAD

**Issue by TuomasKiviaho** [swagger-api/swagger-core#899]
In #846 I wished that proposal for overriding of data type (just by declaring it in string form) could be reconsidered. 

It's quite cumbersome to register a Converter compared to `@XmlSchemaType` (and `@XmlJavaTypeAdapter`) of JAXB. I'd rather declare `@ApiParam(dataType="date") LocalDate date` directly at method param level, so that other tools like swagger-doclet can also utilize the annotation.

I'm ware of `@ApiImplicitParam` that has this feature, but I'm using JAX-RS and this annotation is intended for standalone usage (it provides the `paramType`, it's designed for method level usage and it has quite different semantics despite the similarities).

**Comment by fehguy** [comment]
@TuomasKiviaho thank you for opening a new issue, the other one was hijacked and the title was wrong (it's not missing because it's not supposed to be there).  I do agree with the convenience, it's simply a priority issue.  If you like, you can for the develop_2.0 branch and send a pull request for it.  As long as it's well tested, we'll merge it.

**Comment by fehguy** [comment]
This has been added in https://github.com/swagger-api/swagger-core/commit/9e8b2c6bff639598df077465b9a78ebb854f0b83

**Comment by mikeholtkamp** [comment]
Question does this mean that by the type parameter we can override the schema ref property?
