### ISSUE TITLE
Migrate swagger-servlet module

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#919]
The servlet module allows users to work in any java framework.  Need to move this to 1.5.x

**Comment by webron** [comment]
#1090 should cover this one.

**Comment by zyro23** [comment]
could the reader class for this be implemented in a fashion so that jax rs annotations/classes are supported but their use is not mandatory to annotate an api?

what i am after is to use only swagger annotations to annotate an api staying more agnostic wrt the actual rest implementation that is used, including a way to map any method to an arbitrary path.

i think currently, the only missing part is a `@ApiPath` (or similar) annotation which can be used to express the path a method maps to (current servlet reader impl. uses the `value` of `@Api` for all `@ApiOperation`-annotated methods).

besides that, using `@Api`, `@ApiImplicitParam`, `@ApiImplicitParams`, `@ApiOperation`, `@ApiResponse` and `@ApiResponses` works reasonably well to completely annotate resources/classes where methods represent paths.

thanks, zyro

**Comment by webron** [comment]
I honestly don't understand what you're trying to achieve.

**Comment by zyro23** [comment]
essentially i want to be able to annotate an api using the swagger-servlet module without using jax-rs as rest impl. that includes allowing multiple methods within one class/resource to be mapped to different paths.

**Comment by webron** [comment]
You'd need to give a concrete example (that is, code) to explain the use case. I don't see how it's related to servlet module at all.

**Comment by zyro23** [comment]
https://gist.github.com/zyro23/c5be1b659a2de22f12f9
that gist shows a simplified grails controller (a rest resource) with two operations. those two methods should be mapped to different paths. it would be nice if that could be expressed with swagger annotations in a way that the migrated swagger-servlet reader impl. is able to parse.
i hope u do not mind using grails as example (groovy syntax..). this should not be specific to any framework or any rest implementation.

hope that helps? if this is not the right place for this kind of discussion or that request, im happy to open a new issue.

**Comment by webron** [comment]
I think I get what you're trying to suggest here, as a generic way to describe APIs which is implementation-agnostic. While it's an interesting idea, it's a bit out of scope for this issue. Right now, our main drive is to migrate the 1.3 module to 1.5.

To support what you want, we may need to plan it further and it *may* be an expansion/generalization of the servlet module. You can open a new issue as a feature request, but I cannot guarantee high prioritization.

**Comment by zyro23** [comment]
thank you. ill give the migrated swagger-servlet module a spin once it is in shape and then raise this idea again as a new issue if still necessary.
